// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.0--rc1
// source: arith.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ArithSerive_Multiply_FullMethodName = "/pb.ArithSerive/Multiply"
)

// ArithSeriveClient is the client API for ArithSerive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithSeriveClient interface {
	Multiply(ctx context.Context, in *ArithRequst, opts ...grpc.CallOption) (*ArithResponse, error)
}

type arithSeriveClient struct {
	cc grpc.ClientConnInterface
}

func NewArithSeriveClient(cc grpc.ClientConnInterface) ArithSeriveClient {
	return &arithSeriveClient{cc}
}

func (c *arithSeriveClient) Multiply(ctx context.Context, in *ArithRequst, opts ...grpc.CallOption) (*ArithResponse, error) {
	out := new(ArithResponse)
	err := c.cc.Invoke(ctx, ArithSerive_Multiply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithSeriveServer is the server API for ArithSerive service.
// All implementations must embed UnimplementedArithSeriveServer
// for forward compatibility
type ArithSeriveServer interface {
	Multiply(context.Context, *ArithRequst) (*ArithResponse, error)
	mustEmbedUnimplementedArithSeriveServer()
}

// UnimplementedArithSeriveServer must be embedded to have forward compatible implementations.
type UnimplementedArithSeriveServer struct {
}

func (UnimplementedArithSeriveServer) Multiply(context.Context, *ArithRequst) (*ArithResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedArithSeriveServer) mustEmbedUnimplementedArithSeriveServer() {}

// UnsafeArithSeriveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithSeriveServer will
// result in compilation errors.
type UnsafeArithSeriveServer interface {
	mustEmbedUnimplementedArithSeriveServer()
}

func RegisterArithSeriveServer(s grpc.ServiceRegistrar, srv ArithSeriveServer) {
	s.RegisterService(&ArithSerive_ServiceDesc, srv)
}

func _ArithSerive_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArithRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithSeriveServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArithSerive_Multiply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithSeriveServer).Multiply(ctx, req.(*ArithRequst))
	}
	return interceptor(ctx, in, info, handler)
}

// ArithSerive_ServiceDesc is the grpc.ServiceDesc for ArithSerive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArithSerive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ArithSerive",
	HandlerType: (*ArithSeriveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _ArithSerive_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arith.proto",
}
